### ISSUE TITLE
e.encryptedChunk(...)

### ISSUE THREAD

**Issue by legarspol** [dchest/nacl-stream-js#2]
Hi !
Trying to bring this to java and I hope the tests will help me.
But does tests even run ?
I can't get how that line should behave:
```java
  t.throws(function() { e.encryptedChunk(data.subarray(0, 1000)); }, Error, 'should throw if encryptChunk called after last chunk');
```

Isn't it supposed to be `e.encryptChunk` instead of `e.encryptedChunk()`  ?
I don't see any method called encryptedChunk, maybe is it because of my poor knowledge in javascript.
Thanks for your help ! :-)

**Comment by dchest** [comment]
Ha, of course! Thanks for noticing. The test worked because it threw exception about non-existent function, but this is not what we were intending to test.

**Comment by legarspol** [comment]
One more blind guess:
You may consider replacing `e` variable by `d` in this line:

```java
t.throws(function() { e.decryptChunk(chunks[0]); }, Error, 'should throw if decryptChunk called after last chunk');
```

https://github.com/dchest/nacl-stream-js/blob/master/test/test.js line 44

**Comment by dchest** [comment]
Indeed, thanks again!
