### ISSUE TITLE
length is unauthenticated

### ISSUE THREAD

**Issue by dominictarr** [dchest/nacl-stream-js#3]
There is a minor bug in this library, but in a crypto module every minor bug is serious.
Basically, since the length is unauthenticated it's possible to alter it and this can cause the application to deadlock in certain cases. I have a detailed description of this bug affecting another library [here](https://github.com/calvinmetcalf/hmac-stream/issues/5)

It may be unlikely that a given application would be realistically harmed by this attack, but if it exists, it means you have to audit each application to check it doesn't use a given cryptotool in an unsafe way, which is much harder than just auditing the one crypto library.

I also have a similar streaming protocol here that does not have this bug, which you may be interested
https://github.com/dominictarr/pull-box-stream (it's also based on nacl)

**Comment by dchest** [comment]
Thank you for raising the issue! After thinking for 10 minutes, I don't see how this is a legitimate attack on the cryptographic protocol: the ultimate, cheapest scenario in the described attack for the attacker who can modify packets is to not retransmit the packet at all. If an application is not designed to have measures against this (e.g. timeouts), it will fall into the deadlock. I'll think about this more, and would like to listen to arguments.

**Comment by dominictarr** [comment]
Okay I'll accept the timeout thing, if you add timeouts to this module, or at the very least, document that requirement clearly.

I can't really make a rock solid, you-absolutely-should-do-this argument, but I can explain my philosophy on this: The security layer should be self contained and should not depen on the other layers. That means, you should be sure of the security properties by auditing the security layer. The only way you know a system is correct is by testing it, so optimize for testing - the easiest way is to split it into clearly defined modules, and test those well. To know a system is secure, we need to audit it. Auditing is hard (as is testing) so we need to optimize for auditability - just like modular development optimizes for testability. If the security of an application depends on both the security parts and the rest of the application parts, then you need to audit the whole thing, this is a lot more work than if you can be sure of the security properties by auditing the security parts.

So, the ideal, is if you get your security properties via the cryptoprotocol. So, using the method I propose, you can be sure of the length cryptographically, but if you rely on timeouts, you have to be sure that the other end, the peer with whom you are communicating with, has implemented the timeouts correctly.

If you don't have access to the other machine, you can't know they have timeouts correct (without invoking timeout errors, and checking it doesn't stall) but with a cryptographic assurance, you can tell that for them to be able to execute the protocol correctly, they are also assured of the properties!

So, I think this is a good security engineering principle.

**Comment by dchest** [comment]
I'm sorry, but I still fail to see how I can solve the problem of not having proper timeouts in the application in this crypto library.

Let's start with a solution — what do you think will fix this issue?
