### ISSUE TITLE
[Question] Usable?

### ISSUE THREAD

**Issue by elimisteve** [dchest/nacl-stream-js#6]
Would you recommend using this library in production despite its alpha status?

If not, is there a JS implementation of NaCl or libsodium for streaming encryption/decryption you'd recommend instead?

Thanks!

**Comment by dchest** [comment]
Yes, it's usable, it's used in miniLock and older version of Peerio. No issues. I guess I need to remove "alpha" status.

**Comment by dchest** [comment]
I've just updated it to TweetNaCl 1.0 and removed alpha warning.

**Comment by elimisteve** [comment]
Thank you :+1:
